server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-order-service  # 服务发现需要

# OpenFeign超时控制
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

# OpenFeign日志打印功能
logging:
  level:
    com.codeman.springcloud.service.PaymentFeignService: debug

